name: Delete

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        # 创建一个临时分支来保存当前工作树的内容
        git checkout --orphan branch
        # 在此分支上添加初始提交
        git add -A
        git commit -am "commit message"
        # 删除 main 分支的历史
        git branch -D main
        # 将 branch 重命名为 main
        git branch -m main
        # 强制推送到远程以覆盖旧历史
        git push origin main --force
