# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: iptest_update

on:
  workflow_dispatch:
    inputs:
      path:
        description: '请输入要合并csv/xlsx的路径'
        required: false
        default: ipfofa

permissions:
  contents: write
  discussions: write

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Get current date with dot separator
      id: current_date
      run: |
        echo "DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
    - name: build 
      run: |
        cd iptest
        npm i
        node  csv_hb.js init.csv ./${{ github.event.inputs.path }}
    - name: delete
      run: |
        cd iptest
        rm -rf locations.json iptest ipfofa ipquake node_modules ip_tq.csv ip_init.txt *数据.csv
        tar --no-recursion -czvf iptest.tar.gz *
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          name: IPtest 工具 ${{ env.DATE }}
          files: iptest/iptest.tar.gz
          tag_name: v.iptest
          append_body: false
          generate_release_notes: true
          body: |
            使用教程请查看 https://github.com/Lycofuture/MarketNest/blob/main/iptest/README.md
    - run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add iptest/init.csv
        if ! git diff --cached --quiet; then
          git commit -m "csv update ${{ env.DATE }}"
          git push
        fi
